### ISSUE TITLE
Player is not moving after pressing Space

### ISSUE THREAD

**Issue by itsharshdeep** [hainam125/FFTA-Demo#1]
Hi,

Thanks for publishing the code. I have downloaded your code and as you have displayed in your video the player is not moving from its position after pressing the SpaceBar. Would you please check the same on your side or add a small ReadMe.txt to let us know the controls. 

Thanks once again 

Inderdeep

**Comment by hainam125** [comment]
Hi,
For moving:
 - First you need to move the cursor to Player and press Space Bar.
 - Then, move the cursor to another tile and press Space Bar again.

Please check.

**Comment by itsharshdeep** [comment]
Thanks it worked
